Traceback (most recent call last):
  File "/home/ihubnvidia20/vqe4.py", line 78, in <module>
    fc_problem = fc_transformer(problem)
TypeError: 'FreezeCoreTransformer' object is not callable
